volumes:
  gitea:
    driver: local
  gitea-config:
    driver: local
  gopher-bot_config:
    external: true
    name: gopher-bot_config
  gopher-bot_ssh:
    external: true
    name: gopher-bot_ssh

networks:
  gitea-network: {}

services:
  gitea:
    image: gitea/gitea:latest-rootless
    userns_mode: keep-id:uid=1000,gid=1000
    restart: always
    volumes:
      - gitea:/var/lib/gitea
      - gitea-config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "2222:2222"
    networks:
      - gitea-network

  gopher-bot:
    build:
      context: ../..
      dockerfile: ./deployments/gopher-bot/Dockerfile
    restart: always
    volumes:
      - gopher-bot_config:/etc/gopher-bot
    ports:
      - "8080:8080"
    networks:
      - gitea-network
